# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: none
schedules:
- cron: "0 9 * * *"
  displayName: Every day at 9 am(utc) (오후 6시)
  branches:
    include:
    - develop
  always: true


variables:
  pythonVersion: '3.8'

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    sandboxData:
      variables:
      - group: Billing.AzureSandBoxCrawler.vg
    prodData:
      variables:
      - group: Billing.AzureCrawler.vg

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
  displayName: 'Use Python $(pythonVersion)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    export PYTHONPATH=$PYTHONPATH:$(System.DefaultWorkingDirectory)
    python main.py --daily-usage --database-password $(DATABASE_PASSWORD) --app-secret $(SECRET)
  displayName: 'crawler'
