# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger: none
schedules:
- cron: "0 9 10 * *"
  displayName: Every month at 10th 8 am(utc) (매월 10일 오후 5시)
  branches:
    include:
    - pyodbc
  always: true


variables:
- group: Billing.AzureCrawler.vg

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
    curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
    sudo apt-get update
    sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
  displayName: 'Install MS OSBC Driver'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    export PYTHONPATH=$PYTHONPATH:$(System.DefaultWorkingDirectory)
    python main.py --price-update --database-password $(DATABASE_PASSWORD) --app-secret $(SECRET)
  displayName: 'crawler'
